// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukscirhrsemnwlatqjyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrc2Npcmhyc2VtbndsYXRxanlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTcyNDQsImV4cCI6MjA2Mzc3MzI0NH0.HctgzPlvSy5thUAUsDsFwfTR57dFbf6SbOCxASuYA4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);